display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« Premier'
            last: 'Dernier »'
    display_title: Maître
