display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
          tags:
            previous: "‹\_précédent"
            next: "suivant\_›"
            first: "«\_premier"
            last: "dernier\_»"
      fields:
        state:
          label: État
        label:
          label: Étiquette
        source_language_1:
          label: 'A partir de'
        target_language:
          label: À
        translator:
          label: Fournisseur
        progress:
          label: Progression
        word_count:
          label: Mots
        tags_count:
          label: Étiquettes
        changed:
          label: Modifié
        operations:
          label: Actions
      filters:
        state:
          expose:
            label: État
        source_language:
          expose:
            label: 'Langue d''origine'
        translator:
          expose:
            label: Fournisseur
  page_1:
    display_options:
      menu:
        title: Travaux
      tab_options:
        title: Travaux
