display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Zur√ºcksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      fields:
        nothing:
          admin_label: Symbol
        type:
          label: Typ
        message:
          label: Nachricht
        name:
          label: Benutzer
        link:
          label: Aktionen
      filters:
        type:
          expose:
            label: Typ
  page:
    display_title: Seite
