label: Inhalt
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ Vorherige Seite'
            next: 'Nächste Seite ›'
            first: '« Anfang'
            last: 'Ende »'
      fields:
        title:
          label: Titel
        type:
          label: Inhaltstyp
        status:
          label: Status
        operations:
          label: Aktionen
      filters:
        title:
          expose:
            label: Titel
        type:
          expose:
            label: Inhaltstyp
        status:
          expose:
            label: Status
        langcode:
          expose:
            label: Sprache
      title: Inhalt
  page_1:
    display_options:
      menu:
        title: Inhalt
      tab_options:
        title: Inhalt
    display_title: Seite
