display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
          tags:
            previous: '‹ Vorherige Seite'
            next: 'Nächste Seite ›'
            first: '« Anfang'
            last: 'Ende »'
      fields:
        state:
          label: Status
        label:
          label: Beschriftung
        type:
          label: Typ
        source_language:
          label: Von
        target_language:
          label: An
        progress:
          label: Fortschritt
        word_count:
          label: Wort
        tags_count:
          label: Tags
        changed:
          label: Geändert
        operations:
          label: Aktionen
      filters:
        state:
          expose:
            label: Status
          group_info:
            label: Status
        source_language:
          expose:
            label: Ausgangssprache
        target_language:
          expose:
            label: Zielsprache
        job_type:
          group_info:
            label: Job-Typ
            group_items:
              2:
                title: Fortlaufend
      title: Auftragselemente
  page_1:
    display_title: Seite
    display_options:
      menu:
        title: Auftragselemente
