display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
          tags:
            previous: '‹ Vorherige Seite'
            next: 'Nächste Seite ›'
            first: '« Anfang'
            last: 'Ende »'
      fields:
        status:
          label: Status
        progress:
          label: Fortschritt
        label:
          label: Beschriftung
        item_type:
          label: Typ
        word_count:
          label: Wörter
        operations:
          label: Aktionen
      arguments:
        tltid:
          exception:
            title: Alle
